#!/usr/bin/env sh

echo "### Versions ###"
echo
! type openvpn >/dev/null 2>&1 || { echo -n "* openvpn : " ; openvpn --version | head -1 ; }
! type saml2aws >/dev/null 2>&1 || { echo -n "* saml2aws: " ; saml2aws --version | head -1 ; }
! type aws >/dev/null 2>&1 || { echo -n "* aws-cli: " ; aws --version | head -1 ; }

test ! -s "./README.md" || {
  echo
  echo "### Usage ###"
  sed -ne '/^### Usage ###/,/^### /{/^### /!p}' ./README.md
}
